controller_server:
  ros__parameters:
    controller_frequency: 20.0
    progress_checker_plugin: "nav2_controller::SimpleProgressChecker"
    goal_checker_plugin: "nav2_controller::SimpleGoalChecker"
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      critics: ["GoalDistCritic", "PathDistCritic", "ObstacleFootprintCritic", "PreferForwardCritic"]

      # Parameters for the critics
      GoalDistCritic:
        scale: 24.0
      PathDistCritic:
        scale: 32.0
      ObstacleFootprintCritic:
        scale: 0.02
      PreferForwardCritic:
        scale: 10.0