amcl:
  ros__parameters:
    use_sim_time: False
    min_particles: 500
    max_particles: 2000
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    laser_lambda_short: 0.1
    update_min_a: 0.1
    update_min_d: 0.25
    z_hit: 0.8
    z_short: 0.1
    z_max: 0.05
    z_rand: 0.05

planner_server:
  ros__parameters:
    use_sim_time: False
    expected_planner_frequency: 20.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      max_planning_time: 5.0
      max_retries: 3
      intermediate_waypoints: True

controller_server:
  ros__parameters:
    use_sim_time: False
    controller_frequency: 20.0
    progress_checker_plugin: "progress_checker/ProgressChecker"
    goal_checker_plugin: "goal_checker/GoalChecker"
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      costmap_topic: local_costmap/costmap
      critic_plugins: ["GoalDistCritic", "PathDistCritic", "ObstacleFootprintCritic"]
      GoalDistCritic:
        scale: 24.0
      PathDistCritic:
        scale: 32.0
      ObstacleFootprintCritic:
        scale: 0.01

costmap_common_params:
  global_costmap:
    ros__parameters:
      global_frame: "map"
      robot_base_frame: "base_link"
      update_frequency: 1.0
      publish_frequency: 1.0
      resolution: 0.05
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        enabled: True
      obstacle_layer:
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          sensor_frame: laser_frame
          data_type: LaserScan
          inf_is_valid: True
      inflation_layer:
        enabled: True
        inflation_radius: 0.55

  local_costmap:
    ros__parameters:
      global_frame: "odom"
      robot_base_frame: "base_link"
      update_frequency: 5.0
      publish_frequency: 2.0
      resolution: 0.05
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          sensor_frame: laser_frame
          data_type: LaserScan
          inf_is_valid: True
      inflation_layer:
        enabled: True
        inflation_radius: 0.55
