slam_toolbox:
  ros__parameters:
    use_sim_time: False
    slam_mode: True
    map_update_interval: 2.0
    resolution: 0.1
    max_laser_range: 8.0
    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.1
    mode: "mapping"
    publish_period: 1.0
    map_frame: "map"        # Ensure this is set
    base_frame: "base_link"  # Set the robot's base frame
    odom_frame: "odom"       # Ensure odom frame is set